# Generated by Django 6.0 on 2025-12-23 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tickets', models.PositiveIntegerField()),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('tickets_held', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
