# Generated by Django 6.0 on 2025-12-22 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('price_cents', models.PositiveIntegerField()),
                ('total_tickets', models.PositiveIntegerField()),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('tickets_held', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['start_at'], name='catalog_eve_start_a_8703c8_idx'), models.Index(fields=['name'], name='catalog_eve_name_d05a9b_idx')],
            },
        ),
    ]
