# Generated by Django 6.0 on 2025-12-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
