# Generated by Django 6.0 on 2025-12-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_event_image_url_event_global_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='global_image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_content_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_data',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
