# Generated by Django 6.0 on 2025-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
