# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ticketing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ticketing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fticketing.proto\x12\tticketing\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x0fGetEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"\xeb\x02\n\x10GetEventResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x08start_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bprice_cents\x18\x04 \x01(\x05\x12\x15\n\rtotal_tickets\x18\x05 \x01(\x05\x12\x14\n\x0ctickets_sold\x18\x06 \x01(\x05\x12\x14\n\x0ctickets_held\x18\x07 \x01(\x05\x12\x19\n\x11\x61vailable_tickets\x18\x08 \x01(\x05\x12;\n\x08metadata\x18\t \x03(\x0b\x32).ticketing.GetEventResponse.MetadataEntry\x12.\n\ncreated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x12HoldTicketsRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x16\n\x0ereservation_id\x18\x03 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x04 \x01(\x05\"7\n\x13HoldTicketsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\x0e\x43\x61talogService\x12\x43\n\x08GetEvent\x12\x1a.ticketing.GetEventRequest\x1a\x1b.ticketing.GetEventResponse2`\n\x10InventoryService\x12L\n\x0bHoldTickets\x12\x1d.ticketing.HoldTicketsRequest\x1a\x1e.ticketing.HoldTicketsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticketing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETEVENTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_GETEVENTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_GETEVENTREQUEST']._serialized_start=63
  _globals['_GETEVENTREQUEST']._serialized_end=98
  _globals['_GETEVENTRESPONSE']._serialized_start=101
  _globals['_GETEVENTRESPONSE']._serialized_end=464
  _globals['_GETEVENTRESPONSE_METADATAENTRY']._serialized_start=417
  _globals['_GETEVENTRESPONSE_METADATAENTRY']._serialized_end=464
  _globals['_HOLDTICKETSREQUEST']._serialized_start=466
  _globals['_HOLDTICKETSREQUEST']._serialized_end=567
  _globals['_HOLDTICKETSRESPONSE']._serialized_start=569
  _globals['_HOLDTICKETSRESPONSE']._serialized_end=624
  _globals['_CATALOGSERVICE']._serialized_start=626
  _globals['_CATALOGSERVICE']._serialized_end=711
  _globals['_INVENTORYSERVICE']._serialized_start=713
  _globals['_INVENTORYSERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
