# Generated by Django 6.0 on 2025-12-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
